spring:
  application:
    name: Household Inventory
  datasource:
    url: jdbc:postgresql://localhost:5432/household_inventory
    driver-class-name: org.postgresql.Driver
    username: db_user
    password: db_password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
          order_updates: true
          order_inserts: true
    open-in-view: false
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: false
    baseline-version: 0
    validate-on-migrate: true
    locations: classpath:db/migration
logging:
  level:
    root: DEBUG
