services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.0
    command: start-dev --import-realm
    container_name: inventory_keycloak
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/health/ready || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      db:
        condition: service_healthy
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/${KC_DB_NAME}
      KC_DB_USERNAME: ${POSTGRES_USER:? 'Environment variable POSTGRES_USER not set'}
      KC_DB_PASSWORD: ${POSTGRES_USER_PASSWORD:? 'Environment variable POSTGRES_USER_PASSWORD not set'}
      KC_BOOTSTRAP_ADMIN_USERNAME: kc-admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: kc-admin
    ports:
      - "8090:8080"
    volumes:
      - ./keycloak/:/opt/keycloak/data/import/
  db:
    image: postgres:16
    container_name: inventory_db
    environment:
      KC_DB_NAME: ${KC_DB_NAME:? 'Environment variable KC_DB not set'}
      POSTGRES_DB: ${POSTGRES_DB:? 'Environment variable POSTGRES_DB not set'}
      POSTGRES_USER: ${POSTGRES_USER:? 'Environment variable POSTGRES_USER not set'}
      POSTGRES_PASSWORD: ${POSTGRES_USER_PASSWORD:? 'Environment variable POSTGRES_USER_PASSWORD not set'}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h 127.0.0.1 -p 5432 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
  app:
    image: ${IMAGE:-inventory:latest}
    container_name: inventory_app
    depends_on:
      db:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8080/actuator/health/liveness > /dev/null || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_USER_PASSWORD}
volumes:
  db_data: